### ISSUE TITLE
Stack alignment

### ISSUE THREAD

**Issue by edoelsch** [mlerotic/spectromicroscopy#18]
Hello,
I am not familiar with the FFT-cross correlation alignment procedure so I used the default parameters proposed by Mantis (see below).
A consequence of this alignment is the appearance of horizontal and vertical lines that are not visible in the raw data. The problem is that these lines subsequently affect the PCA and Cluster analysis. Does one of the options in the alignment procedure allow for the removal of these lines? I have tried adjusting some parameters, but without success. One last question, is there a guideline available for the alignment procedure?

Thank you in advance.
Cheers,
Emmanuel
![image](https://github.com/mlerotic/spectromicroscopy/assets/169818090/93d4db54-0cce-40de-9f26-b5e3687c7774)

![image](https://github.com/mlerotic/spectromicroscopy/assets/169818090/0e8f55d2-a782-4add-b059-f152b9c8581d)

![image](https://github.com/mlerotic/spectromicroscopy/assets/169818090/ca13ccf4-e4fc-41c1-aa89-add38978ba9f)

**Comment by Grumium** [comment]
Hi Emmanuel,
Thank you for pointing this out. I understand that this is bothering and I think I found a solution. 
Shifting the images via FFT with subpixel accuracy naturally introduces artifacts at objects with high contrasts. This is particularly prominent when particles drift out or into of the field of view. You can easily spot the origin of the artifacts in your example when you uncheck "Auto-crop stack". 

In https://github.com/mlerotic/spectromicroscopy/commit/333046dbe1d2743d88a2257df5440cc6c89c1bf8 I therefore introduced a checkbox to align with lower accuracy (displacement rounded to the full pixel instead of 0.05 px). The artifacts will be gone but the alignment result will be a little wobbly. This can be useful though when you want to "coarse align" a stack at first without "altering" data and apply a second fine-alignment afterwards.

In https://github.com/mlerotic/spectromicroscopy/commit/2d1c791d81747aa93b4a98420631ce03c30b4d6a I developed a method to reduce edge artifacts by padding the image by a certain amount before applying the FFT shift. This is independent from the accuracy checkbox and is enabled by default.

Before: 
![image](https://github.com/mlerotic/spectromicroscopy/assets/47479352/f2a1c50b-8b99-4315-bc71-634eac8fb202)
After:
![image](https://github.com/mlerotic/spectromicroscopy/assets/47479352/bb6b2ab5-5202-4b20-ab7b-bde91fab328a)

Please try out the recent version 3.1.43 and re-open the issue again if the issue persists.
Unfortunately, there is no guideline yet. The default settings work in approx. 90% of the cases for me.

Cheers,
Jan-David
