### ISSUE TITLE
Minor: New SciPy and Matplotlib libraries cause Mantis problems

### ISSUE THREAD

**Issue by urquhart-usask** [mlerotic/spectromicroscopy#22]
I ran into a problem after running `pip3 install mantis-xray -U --upgrade-strategy "eager"`

The current SciPy (1.14.0) and Matplotlib (3.9) versions cause a few errors when running mantis. These went away by loading scipy 1.13.1 and matplotlib 3.8. Rolling back Matplotlib also rolled back numpy to 1.26.4; I don't know which one was important.

I did add the tweaks Ben added in May, so all that's good.

many thanks,
Stephen

**Comment by Grumium** [comment]
This issue was caused by the deprecated functions `trapz`and `get_cmap`:
https://docs.scipy.org/doc/scipy/release/1.12.0-notes.html#deprecated-features
https://matplotlib.org/stable/api/cm_api.html#matplotlib.cm.get_cmap

It has been solved in https://github.com/mlerotic/spectromicroscopy/commit/fd3662c3bae6a7e73aaa5619699fcef701d1e7fd
