### ISSUE TITLE
python 3.13 xdrlib disappears

### ISSUE THREAD

**Issue by urquhart-usask** [mlerotic/spectromicroscopy#28]
I tried to load mantis-xray on a computer with python 3.13 on it.

xdrlib is depreciated in python 3.13. However, the replacement exists - see  https://pypi.org/project/xdrlib3/

A slight change to henke.py is needed to change the line:
from xdrlib**3** import *

**Comment by Grumium** [comment]
Thank you!
Fixed in https://github.com/mlerotic/spectromicroscopy/commit/639fbcc3aa985b7e2bc0faf4d41133c89dbf272a
Instead of posting code in plain text, you could submit a PR. This makes it easier to review, track, and acknowledge your contribution.

**Comment by benajamin** [comment]
I would appreciate if you guys consider that not everyone should be expected to be running the latest versions of everything. I have added some conditions in https://github.com/mlerotic/spectromicroscopy/commit/e0605c0ed7cae8840e3dfcc73d563e1aba8f3474 so that xdrlib3 is only required when using Python>=3.13

**Comment by Grumium** [comment]
Thank you for putting in the effort! The improvement is much appreciated. While this was a relatively small fix, there’s always a point where backward compatibility needs to be sacrificed - but not in this case, I agree.
